### ISSUE TITLE
Лабораторна робота 1

### ISSUE THREAD

**Issue by steminist-ua** [Velvids/LR1#1]
1. У роботі використовуються div та id, що для цієї лабораторної є помилкою. 

Наприклад: 
```html
<div id="header">
<h1>Visual Studio Code - Open Source</h1>
</div>
```

**Comment by steminist-ua** [comment]
2. Оголошення div в середині ul - це помилка. До того ж, div має мати закриваючий тег, але в коді він відсутній. 

```html
<ul>
<div id="cencen">
<li class="smiley">😀</li>
<li class="smiley">😀</li>
<li class="smiley">😀</li>
</ul>
```

**Comment by steminist-ua** [comment]
3. Використання коду в стилях, який є зайвим, очевидно, скопійованим.  
Приклади:
```css
display: inline-block; 
position: relative; 
z-index: 1; 
right: 2%;
```

```css
.smiley::before {
  content: ""; 
  position: absolute; 
  background-color: purple; 
  border-radius: 100%; 
  width: 60px; 
  height: 60px; 
  top: 55%; 
  left: 49%;
  transform: translate(-50%, -50%); 
  z-index: -1; 
}
```

```css
#column {
  display: flex;
  margin-top: 20px;
  flex-direction: column;
  align-items: center;
  background-color: #333333;
  color: white;
}
```

```css
#cencen {
  display: flex;;
  flex-direction: cencen;
  align-items: center;
  justify-content: center;
  padding: 1px;
}
```
